### ISSUE TITLE
Parse "bare" cookies in non-strict mode

### ISSUE THREAD

**Issue by stash** [salesforce/tough-cookie#10]
Some cookies with an empty value can look like `name` instead of `name=`.  These should be parse-able in non-strict mode and round-tip when serializing to strings.

**Comment by stash** [comment]
Triage: should investigate if this is still an issue, sync up with the whatwg reference linked above?

**Comment by stash** [comment]
Related to this: check out http://inikulin.github.io/cookie-compat/ !

**Comment by ruoho** [comment]
Correctly parsing cookies with empty / no key was merged in https://github.com/salesforce/tough-cookie/pull/49. Let's create a new issue if we want to investigate the whatwg reference.
