### ISSUE TITLE
Is It posibale rewrite other user's cookie?

### ISSUE THREAD

**Issue by webaifei** [salesforce/tough-cookie#108]
Hi, i use tough-cookie in my next.js project with Axios.
After fetching data, i use cookiejar.setCookie(cookies, url)  then i use cookiejar.getCookie(url) to get previous cookies for next fetching api (e.g. /getuserinfo)
I am so worried about that User-B's cookie may rewrite User-A's cookie in cookiejar  before User-A getting his info. Because I find the cookie.key may be same when the cookiejar storing cookie .

**Comment by stash** [comment]
That is correct. This is the expected behaviour for cookies using the same URL. Suggest that you create and keep a separate cookie jar per user. For example, you can serialize the jar as JSON and store it in the next.js session (sorry if that's the wrong terminology; I don't know next.js at all)
