### ISSUE TITLE
Can't using setCookie function to load cookie from getCookieString or getCookies?

### ISSUE THREAD

**Issue by KuoKongQingYun** [salesforce/tough-cookie#109]
Can't using setCookie to load cookie from getCookieString or getCookies?
I want to find a quick way to restore and load cookie to/from redis server,
I test getCookieString/setCookie and getCookies/setCookie,but they can't work directly.
The format of the return of getCookieString or getCookies can't be compatible with setCookie,
so I have to translate the format manually?

**Comment by stash** [comment]
Sounds like `redis-cookie-store` would have been a good solution for this https://github.com/benkroeger/redis-cookie-store
