### ISSUE TITLE
Conflicting Paths Generated By permutePath

### ISSUE THREAD

**Issue by duper51** [salesforce/tough-cookie#111]
I'm experiencing a bug using this library when attempting to get a previously set cookie from a JAR using the FileCookieStore() store.

If I set a certain cookie with a path ending in a slash (such as "/cas/"), when I attempt to retrieve it using getCookies using the same URL as the first parameter, the call to `permutePath` returns an Array containing `["/cas", "/"]` which doesn't match "/cas/" which causes the `pathMatcher` `matchRFC` to not find any matching cookies, even though I'm providing the same URL. I'm not entirely sure this is the desired behavior.

**Comment by duper51** [comment]
Just had a look at the PRs and it looks like issue #90 is resolving this issue.

**Comment by ruoho** [comment]
@duper51 Which FileCookieStore were you using?

**Comment by duper51** [comment]
I'm gonna take a look at the code I was using to get this to work, I am not sure which I was using.

**Comment by awaterma** [comment]
We believe this has been fixed in our 4.x release. Please reopen with a test case if there's been a mistake.
