### ISSUE TITLE
Regular Expression Denial of Service 

### ISSUE THREAD

**Issue by TimeBandit** [salesforce/tough-cookie#112]
![tough cookie screenshot from 2018-05-10 17-34-53](https://user-images.githubusercontent.com/2059850/39881316-7b7bc866-5478-11e8-8d8d-c7cca0d5c50a.png)
see => https://nodesecurity.io/advisories/525  
Can you update to use sshpk >=1.14.1?

**Comment by oliverjessner** [comment]
forever-monitor and a lot of more packages are also depending on tough-cookie.

**Comment by stash** [comment]
This DoS is already fixed (see #92) in version >=2.3.3. Dependents need to upgrade to that or a later version.
