### ISSUE TITLE
How to use cookies under subdomain

### ISSUE THREAD

**Issue by fakirpic** [salesforce/tough-cookie#123]
i try to use same cookies in subdomains,

i tried to
					try { jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"]["m."+Object.keys(jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"])]=jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"][Object.keys(jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"])]; } catch(e){}

for able to use the cookies under subdomain. but failed. is there any better way?

				return reqret({
					method : 'POST',
					url : document.getElementById('https').checked?'https://' + config.domain + '/test/':'http://' + config.domain + '/test/',
					jar : jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')],
					headers : {
						'User-Agent' : 'Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36',
						'Referer': 'http://' + config.domain + '/'
					},
					maxAttempts : 15,
					retryDelay : 2000,
					followRedirect : false,
					followAllRedirects : false,
					fullResponse : true,
					timeout : timeoutsure,
					form : data
				}).then(function (body) {
					try { jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"]["m."+Object.keys(jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"])]=jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"][Object.keys(jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')]["_jar"]["store"]["idx"])]; } catch(e){}
					adet++;

					return reqret({
						url :  document.getElementById('https').checked?'https://m.' + config.domain + '/test2/':'http://m.' + config.domain + '/test2/',
						jar : jardata[Buffer.from(line[0]+"-"+line[1]).toString('base64')],
						headers : {
							'User-Agent' : 'Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36',
							'Referer': 'http://m.' + config.domain + '/'
						},
						agent : document.getElementById('https').checked?https__Agent:httpAgent,
						maxAttempts : 15,
						retryDelay : 2000,
						followRedirect : true,
						fullResponse : false,	
						timeout : timeoutsure
					}).then(function (body) {

...

**Comment by medelibero-sfdc** [comment]
Hi @fakirpic, 

  Not sure if this is still an issue for you. If it is can you show me the code for jardata getting created?

Thanks,
Mike

**Comment by awaterma** [comment]
Closing out as we have had no updates on this issue from the OP for over 2 years.
