### ISSUE TITLE
Node dependency breaks in non-node environments

### ISSUE THREAD

**Issue by jkulubya** [salesforce/tough-cookie#125]
Hi,
I'm working on a Nativescript project, where the api surface area is node but not quite. The library depends on the presence the node [net](https://nodejs.org/api/net.html#net_net_isip_input) api. This doesn't exist in NS, and the shim for webpack returns true for isIp and related functions [here](https://github.com/webpack/node-libs-browser/blob/1b67bdeefca87d81792e86278439213a6932170e/mock/net.js#L9). This causes [this line](https://github.com/salesforce/tough-cookie/blob/8302ebc43a11f608eb1c62715e7eb2d38920d32c/lib/cookie.js#L323) to fail. I suggest that you drop the use of the node inbuilt module and use a lib or a handwritten function to check for IPs.

**Comment by stash** [comment]
Wow yeah that mocked `isIP` is pretty awful for `tough-cookie`. That's a really good case for not using it if it's not available.

I found https://www.npmjs.com/package/isipaddress, which does most of what we need. It "over-matches" IP addresses by design, though, which might not be what we need for tough-cookie. For example, `192.168.0.1/24` (IP+CIDR) is considered an IP.

**Comment by gzzhanghao** [comment]
Node implements `isIP*` with RegExp. I think we can copy these functions into our project.
https://github.com/nodejs/node/blob/master/lib/internal/net.js#L7

**Comment by sarneeh** [comment]
I have the same issue with this package. It would be awesome to fix this as there are plenty of use cases to use `tough-cookie` on non-node environments like isomorphic apps (i.e. `next.js`).

**Comment by jkulubya** [comment]
Would this package work?
https://www.npmjs.com/package/is-ip

I've tried it over here and with my quick testing it seems okay.
https://codesandbox.io/s/n7z1jlrwkp?module=%2Fsrc%2Fcomponents%2FHelloWorld.vue

**Comment by sarneeh** [comment]
Thank you very much for this fix! 💃 🎉
