### ISSUE TITLE
console.log(cookie) throws an error

### ISSUE THREAD

**Issue by Somebi** [salesforce/tough-cookie#126]
I'm using async redis store, https://github.com/benkroeger/redis-cookie-store
When trying to output contents of cookie via console.log, it throws an error:

```
/var/local/app/node_modules/tough-cookie/lib/cookie.js:1394
      throw new Error('CookieJar store is not synchronous; use async API instead.');
      ^

Error: CookieJar store is not synchronous; use async API instead.
    at CookieJar.serializeSync (/var/local/app/node_modules/tough-cookie/lib/cookie.js:1394:13)
    at CookieJar.toJSON (/var/local/app/node_modules/tough-cookie/lib/cookie.js:1294:15)
    at JSON.stringify (<anonymous>)

```

**Comment by Somebi** [comment]
using latest "tough-cookie": "^2.4.3",

**Comment by Somebi** [comment]
It seems there is only async version of serialize?

**Comment by Somebi** [comment]
Actually not a cookie, but a whole jar, i'm serializingg object which holds jar inside it.

**Comment by Somebi** [comment]
```
function syncWrap(method) {
  return function() {
    var syncMethodAllowed = CAN_BE_SYNC.indexOf(method);
    if (syncMethodAllowed === -1 && !this.store.synchronous) {
      throw new Error('CookieJar store is not synchronous; use async API instead.');
    }
```
Should be this way. But it seems it's not supporting implementation of:
`Error: getAllCookies is not implemented (therefore jar cannot be serialized)`

But that's already problem of redis store module

**Comment by stash** [comment]
I think you figured it out, but you can't use the redis store module with the synchronous methods. The callbacks required for network I/O is what makes it impossible. This error is expected to be thrown for all stores that don't support synchronous operation.
