### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by hyandell** [salesforce/tough-cookie#129]
Hi tough-cookie folk,

The readme says the license is:  "(tl;dr: BSD-3-Clause with some MPL/2.0)".

Could you clarify what the MPL/2.0 is in regards to?

**Comment by stash** [comment]
Oh, well good news is that the LICENSE file is already updated! It's just the README that wasn't updated as part of 3072afa5d45a42c8390e015cb8f563b30cdc0b2a

**Comment by BarrySpencer** [comment]
Hi Jeremy,

My name is Barry Spencer.  As part of an ongoing effort, I’ve asked if my
personal email address could pleased be removed from github.

I left Salesforce last year.  I’ve asked repeatedly.  I would appreciate
your (or someone’s) help in a his regard.

Thank you!!
Barry Spencer

**Comment by stash** [comment]
> Hi Jeremy, My name is Barry Spencer. As part of an ongoing effort, I’ve asked if my personal email address could pleased be removed from github. I left Salesforce last year. I’ve asked repeatedly. I would appreciate your (or someone’s) help in a his regard. Thank you!! Barry Spencer

I don't work there any more either! Maybe osscore@salesforce.com, @ivarley, or @awaterma can help?

(also: not to be *that guy*, but did the unsubscribe link work?)
