### ISSUE TITLE
Unable to install v3.0.0 on node 6.14.0

### ISSUE THREAD

**Issue by thijskramer** [salesforce/tough-cookie#140]
Since today I'm unable to install tough-cookie on node v6.14.0, because I'm getting the following error: 

`error ip-regex@3.0.0: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.14.0"`

I suspect that the introduction of `ip-regex` in PR #138 (and especially [this commit](https://github.com/salesforce/tough-cookie/commit/eff9118f3c960bc1ed378ebb5ec2e80930cd3138)) causes that, because `ip-regex ^3.0.0` needs at least node v8.

**Comment by gzzhanghao** [comment]
Try `yarn --ignore-engines`

**Comment by thijskramer** [comment]
Yes with that flag I'm able to bypass the issue and install tough-cookie, but does that doesn't solve the actual problem. I think tough-cookie should either depend on an older version of ip-regex, or enforce node  >=8 as well.

**Comment by Turbo87** [comment]
I agree with @thijskramer. Either use `ip-regex@2` which still supports Node 6, or officially drop support for Node 6 and bump the major version of this package too.

**Comment by danieljuhl** [comment]
@Turbo87 wasn't the major version of this package bumped to v3? They could add engines info to package.json and release notes about the breaking change in v3, but I assume that dropping support for Node 6 was the reason behind the bump to v3 for tough-cookie.

**Comment by jrjohnson** [comment]
To be fair `3.0.0` was a major bump that dropped several node versions - maybe the release notes and `package.json` just need to be updated to reflect this.

**Comment by Turbo87** [comment]
@jrjohnson it explicitly only dropped support for Node 4 and below though... (see https://github.com/salesforce/tough-cookie/commit/16ba441c868b833f0c29141fccecfaae5ce4bba5)
