### ISSUE TITLE
Cannot read property secure of undefined

### ISSUE THREAD

**Issue by nonyy** [salesforce/tough-cookie#144]
Sample cookie I am trying to parse is included. Any tips on parsing?
Code:
https://repl.it/repls/ProfitableUnfortunateFossil

**Comment by aranmohyeddin** [comment]
@awaterma august has ended. I also have this issue.

**Comment by awaterma** [comment]
I've created a unit test for this now, working on finding time to resolve the issue.

**Comment by awaterma** [comment]
Could you two try this with the master branch? I can't reproduce this:

https://github.com/salesforce/tough-cookie/compare/master...awaterma:issue%23144_property_secure

**Comment by aranmohyeddin** [comment]
I ended up changing my whole authentication system from session auth to JWT auth because I couldn't make cookies and csrf work:D

**Comment by awaterma** [comment]
This is not a bug. You can't call a method that takes a callback without a callback.

I wonder though, should we make this an API error? To clarify for users?

@medelibero-sfdc

**Comment by awaterma** [comment]
@medelibero-sfdc -- let me know what you think, we can open another issue for error handling in async if we want to. I've got a unit test that proves this out -- that's the latest p/r.

**Comment by medelibero-sfdc** [comment]
@awaterma I agree we should add in some extra error handling for this case so people get at least a more friendly exception. But I agree that this specific issue can be closed out and to create a new issue for the error handling bit.

**Comment by awaterma** [comment]
Let's discuss in our next meeting. I think we should do the same as NodeJS when callers execute async methods incorrectly; which may very well be nothing. Let's investigate and create a story for how we want things to be, and then prioritize. :)
