### ISSUE TITLE
Missing parameter validation on setCookie function causes TypeError

### ISSUE THREAD

**Issue by FabianTe** [salesforce/tough-cookie#145]
I noticed missing parameter validation in the `setCookie` function:

https://github.com/salesforce/tough-cookie/blob/43507052a70751501d52aad38bd837bb2edfedd8/lib/cookie.js#L995-L1001

There is no parameter validation which may cause confusion when not setting `url`. If only `cookies` then the function will assume that the `options` parameter is an object and tries to access the `loose` property. This will cause a TypeException.

There should either be parameter validation throwing an Error or some kind of handling.

This was found when investigating this bug: https://github.com/valeriangalliat/fetch-cookie/issues/35

**Comment by stash** [comment]
Agree that this could have a much better error raised than `TypeError`. Pull request would be welcome :)

Other methods besides `setCookie` could benefit from clearer error messages too, for what it's worth.

**Comment by ruoho** [comment]
@FabianTe Sorry for the delay, this should be fixed in the latest pull request. Can you verify?
