### ISSUE TITLE
Add `defaultDomain` option to `Cookie.parse`

### ISSUE THREAD

**Issue by sindresorhus** [salesforce/tough-cookie#149]
I need to accept cookie strings from users where the `Domain` part is optional, since I want it to behave like the browser, which defaults to the current domain.

I currently use this:

```js
toughCookie.parse('color=black').serializeSync();
```

But it throws as there is no `Domain` parameter in the cookie string.

I would like to be able to use it like this:

```js
const object = toughCookie.parse('color=black', {defaultDomain: domain}).serializeSync();
```

Would also be useful to have a `defaultUrl` option, so I don't have to parse the domain from the URL myself.

My current workaround is this, which is quite verbose:

```js
const jar = new toughCookie.CookieJar();
jar.setCookieSync('color=black', url);
const object = jar.serializeSync().cookies[0];

**Comment by stash** [comment]
I'm not sure a defaultDomain option makes sense. I would parse the cookie and check the `.domain` property. Perhaps something like this code would work for you?

Initialization:
```js
const defaultDomain = toughCookie.canonicalDomain(domain);
```

Then, for each cookie:
```js
let cookie = toughCookie.parse(someString);
if (!cookie.domain) cookie.domain = defaultDomain;
const serialized = cookie.toJSON();
```
