### ISSUE TITLE
ip-regex dependency breaks on old very old node versions

### ISSUE THREAD

**Issue by Ankcorn** [salesforce/tough-cookie#150]
Hi, 

I'm currently working on a project using a specific (very old) node version. 

ip-regex's use of es6 features makes our application crash on startup  with this new update and because we have no control over the library pulling in tough cookie we cannot backport to version 2.5 easily and might have to deal with breakages in the future. 

Would it be possible to remove ip-regex as a dependency?

Thanks
Tom

**Comment by amol-c** [comment]
Facing the same issue here.

**Comment by awaterma** [comment]
Ip-regex has been removed as a dependency:

https://github.com/salesforce/tough-cookie/blob/master/package.json#L104
