### ISSUE TITLE
Storing wrong domain when calling setCokies() with IPv6 address

### ISSUE THREAD

**Issue by vikiCoder** [salesforce/tough-cookie#153]
Hi,

I noticed that while storing cookies for URL with IPv6 address (i.e. `http://[::1]/foo`), tough-cookie stores domain name without `[ ]` (i.e. `::1`) in the store. It should store the domain as it is like Chrome does (i.e. `[::1]`).

Because of this behavior, I get error `Error: Cookie not in this host's domain. Cookie:[::1] Request:::1` while executing following code snippet:

```javascript
var tough = require('tough-cookie');
var jar = new tough.CookieJar();
var cookieString = 'my_cookie=hello_world; path=/; domain=[::1]; Expires=Sat, 11 May 2019 11:05:21 GMT;';
var url = 'http://[::1]/';

jar.setCookie(cookieString, url, (e) => {
    console.log(e)
});
```

**Comment by vikiCoder** [comment]
I further looked up in the source code for this.

I think the reason behind this behavior is Node's `url.parse()` function which is being used in `getCookieContext()` of `cookie.js` file.

`url.parse()` removes `[ ]` from hostname. I think it should use the [WHATWG URL API](https://nodejs.org/dist/latest-v11.x/docs/api/url.html#url_the_whatwg_url_api) of Node (which more closely resembles the parsing behavior of most browsers) instead of deprecated [legacy URL API](https://nodejs.org/dist/latest-v11.x/docs/api/url.html#url_legacy_url_api). (i.e. use `new url.URL()` in place of `url.parse()`) This will solve the problem as far as I know.

Correct me if I am missing something.

**Comment by awaterma** [comment]
Closing out; issue was fixed in a merged p/r.
