### ISSUE TITLE
setting rejectPublicSuffixes to false leads to "CookieJar store is not synchronous; use async API instead." error

### ISSUE THREAD

**Issue by skleeschulte** [salesforce/tough-cookie#165]
When I set `rejectPublicSuffixes` to `false`, `setCookieSync` throws "CookieJar store is not synchronous; use async API instead.".

Example: 

    const tough = require('tough-cookie');
    const cookieJar = new tough.CookieJar({ rejectPublicSuffixes: false });
    cookieJar.setCookieSync('name=value', 'http://cookietest.local/');

Am I missing something or is this a bug?

**Comment by medelibero-sfdc** [comment]
This is not a bug. You just need to call `setCookie` instead of `setCookieSync`.
