### ISSUE TITLE
CHANGELOG for v3.0.1 (and older) missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [salesforce/tough-cookie#171]
I just saw the package is updated to `v3.0.1`, but I can't find any CHANGELOG to check out the changes.

Would you be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

**Comment by joepie91** [comment]
Having quickly skimmed the list of commits, it seems that the only breaking change in `v3.0.0` was a bump of the minimum supported Node version (ref [1](https://github.com/salesforce/tough-cookie/commit/16ba441c868b833f0c29141fccecfaae5ce4bba5), [2](https://github.com/salesforce/tough-cookie/pull/138#issuecomment-453765756)).

Of course, a proper CHANGELOG is still needed...

**Comment by ShivanKaul** [comment]
Hi all, we've had a change of personnel actively volunteering for this project, and we've been busy closing PRs and doing a 4.0.0 release. A CHANGELOG for 4.x onwards was added in https://github.com/salesforce/tough-cookie/pull/189 but if there's interest in having a retroactive CHANGELOG, PRs welcome!

**Comment by awaterma** [comment]
We have a new one and we intend on maintaining it going forward.
