### ISSUE TITLE
Broken in Jest again

### ISSUE THREAD

**Issue by pasieronen** [salesforce/tough-cookie#175]
This commit added a workaround for behavior that occurs when using tough-cookie in Jest tests:
https://github.com/salesforce/tough-cookie/commit/d94532db9ea3c971c87224967a4187c4d3ba4981#diff-d721bcd439ec1bdd00213161a426ebd8

But it looks like the recent refactoring in this commit removed this workaround...
https://github.com/salesforce/tough-cookie/commit/08f81419c5beaaa8d076c9eb062f628f258525ae

**Comment by awaterma** [comment]
Could you please submit a p/r with a unit test so we can keep this from occurring again?

**Comment by awaterma** [comment]
Otherwise, we'll try to get to this when we can. I'll bring up this issue in our next meeting.

**Comment by pasieronen** [comment]
@awaterma It took a while to figure out how to create a function that is not `instanceof Function`, but now PR #178 has unit test for this.
