### ISSUE TITLE
 Error during installation

### ISSUE THREAD

**Issue by wenyufei2018** [salesforce/tough-cookie#179]
![捕获](https://user-images.githubusercontent.com/41943990/71543689-d0115080-29b0-11ea-946d-91e2a352ead8.PNG)
Please help me, thank you.

**Comment by medelibero-sfdc** [comment]
Hi @wenyufei2018,

  How did you try to use tough-cookie? Did you run `npm install` before use? 

Thanks,
Mike

**Comment by wenyufei2018** [comment]
hi, @medelibero-sfdc 

You are right. I do not use tough-cookie.In the bug report, but I found tough-cookie.I don't know why !

Fortunately, I solved the problem by another way.

Thank you for your reply！
