### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by david-soyez** [salesforce/tough-cookie#190]
Meteor build issue brought me here:

https://github.com/salesforce/tough-cookie/blob/master/lib/cookie.js#L40
`const { fromCallback } = require("universalify");`

```
W20200320-20:35:52.502(0)? (STDERR) const { fromCallback } = require("universalify");
W20200320-20:35:52.503(0)? (STDERR)       ^
W20200320-20:35:52.503(0)? (STDERR)
W20200320-20:35:52.504(0)? (STDERR) SyntaxError: Unexpected token {
W20200320-20:35:52.504(0)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20200320-20:35:52.505(0)? (STDERR)     at /var/app/.meteor/local/build/programs/server/boot.js:287:30
W20200320-20:35:52.506(0)? (STDERR)     at Array.forEach (native)
```

**Comment by awaterma** [comment]
We discussed this a bit in p/r 157: https://github.com/salesforce/tough-cookie/pull/157#discussion_r350487135. All versions of NodeJS we support,  *should* handle destructuring parameters, as do modern browsers, so I'm not sure what's going on. More background on this feature [available here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

Could you please let us know what version of Node are you using? Could you also please reference the Meteor build issue, so we could take a deeper look?

**Comment by ShivanKaul** [comment]
Closing this, please feel free to re-open if the problem persists!
