### ISSUE TITLE
Loose mode flag is not preserved in toJSON() serialization

### ISSUE THREAD

**Issue by sidx1024** [salesforce/tough-cookie#195]
`CookieJar.toJSON()` method doesn't preserve looseMode flag. Thus, setting an invalid cookie throws an error (after creating a new instance using `fromJSON()`).

Reproduceable code:
```js
const { CookieJar } = require('tough-cookie');

const url = 'http://random.com';
const cookie = 'Invalid Cookie;';

const cookieJar = new CookieJar(null, { looseMode: true });

const deserializedCookieJar = CookieJar.fromJSON(cookieJar.toJSON());
deserializedCookieJar.setCookieSync(cookie, url);
// ^ throws "Error: Cookie failed to parse"
```

**Comment by medelibero-sfdc** [comment]
Hi @sidx1024,

  I can recreate this problem. Let me talk with the rest of the team and figure out the best course of action to fix it.

Thanks,
Mike

**Comment by medelibero-sfdc** [comment]
Hi @sidx1024,

  I have committed to master a fix for this issue. Thank you for reporting this to us! 

-Mike
