### ISSUE TITLE
Store's putCookie never called from setCookie?

### ISSUE THREAD

**Issue by MauriceArikoglu** [salesforce/tough-cookie#212]
I am having issues with a custom Store's methods not being called. I looked through the code in this repo and it seems CookieJar never calls store.putCookie from within setCookie (or any other method)?

**Comment by medelibero-sfdc** [comment]
Hello @MauriceArikoglu,

  What do you mean by using a "custom Store's method"? Can you post some of the code you are trying to use so I can replicate the issue?

  Thanks,
  Mike

**Comment by MauriceArikoglu** [comment]
@medelibero-sfdc hey, thanks for looking into this.
You can setup a spike project and setup a plain object conforming to the Store interface. You will notice its setCookie / putCookie method is never called on CookieJar.setCookie.

Have a look at the implementation for CookieJar.setCookie here: https://github.com/salesforce/tough-cookie/blob/1b25269dbb0478232f910c26386b3cac4ec9d857/lib/cookie.js#L1094

If you follow the method implementation you will notice there is no path where putCookie will be called...

**Comment by MauriceArikoglu** [comment]
The full method in question, as its quite big and not so straightforward:

https://github.com/salesforce/tough-cookie/blob/1b25269dbb0478232f910c26386b3cac4ec9d857/lib/cookie.js#L1094-L1277

**Comment by medelibero-sfdc** [comment]
Yes, and putCookie is called on lines 1240 and 1272.

**Comment by MauriceArikoglu** [comment]
@medelibero-sfdc 
You are right. It seems I lost my ability to read. My bad.

Still, I observed putCookie not being called on my custom Store...

**Comment by medelibero-sfdc** [comment]
Hi @MauriceArikoglu,

  What do you mean by your custom store? Can you show me the code that is not working?

-Mike

**Comment by MauriceArikoglu** [comment]
@medelibero-sfdc https://gist.github.com/MauriceArikoglu/0734e2a09ee81d15e0f1c39ad80b39f8

**Comment by MauriceArikoglu** [comment]
@awaterma I think it isn't. I am not a part of the project anymore. IIRC I used a workaround, but it also might've been a mistake on my end. Can be closed I guess :)
