### ISSUE TITLE
Enable Project for use by Typescript Libraries

### ISSUE THREAD

**Issue by awaterma** [salesforce/tough-cookie#217]
We think it would be a good idea to enable this project for use with typescript. We'd want to do this in chunks over time, or in a large pull request that could be reviewed by the team. 

https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by wjhsf** [comment]
[@types/tough-cookie](https://www.npmjs.com/package/@types/tough-cookie) exists as a community effort. We can definitely provide our own type definitions eventually, but it doesn't necessarily need to be prioritized.

**Comment by awaterma** [comment]
From discussion, it looks like @types/tough-cookie is only supplying types for the Callback versions of our API. So, we may want to invest some effort here to make this clearer in that project, or bundle our own, as we suggest at the top.

@colincasey has committed to take a deeper look at this issue for us.

**Comment by wjhsf** [comment]
Completed as of our [v5 release](https://github.com/salesforce/tough-cookie/releases/tag/v5.0.0)!
