### ISSUE TITLE
Request with tough cookie causes Seg Fault

### ISSUE THREAD

**Issue by osxpinot** [salesforce/tough-cookie#22]
Hello,

Thank you for your work. The follow code causes a segmentation fault, crashing my app.

``` javascript
request({url:"http://www.google.com", jar:myJar}, funciton(err, resp, body){

    //crashes if cookies are not 'ready' here
    console.log(JSON.stringify(myJar));
    //If output: "mycookie=1234;"   SEGMENTAION FAULT
    //If output: "{_jar...}"        FINE   
    request({url:"http://www.google.com", jar:myJar}, funciton(err, resp, body){})
})
```

Unfortunately, I lost the stack trace, which could only be obtained by running through gdb with a specially compiled version of node. 

But it seems that whatever data is getting passed into tough cookie, is causing a problem at this line:
https://github.com/goinstant/tough-cookie/blob/master/lib/cookie.js#L770

The debugger says this: CHECK(object->IsSmi()) failed

Thank you.

**Comment by inikulin** [comment]
Seems like a bug in the one of the unstable versions of node, rather than issue with tough-cookie. 
@osxpinot Can you confirm that issue still exists with the stable node 12 or 10 or io.js?
