### ISSUE TITLE
[RFC] Support for React Native

### ISSUE THREAD

**Issue by lb90** [salesforce/tough-cookie#222]
Hello, thanks for the good work!

I have been using this library on React Native (together with Axios) and so far it's been working ok!

I only had to remove some debug code using the utils module: https://github.com/lb90/tough-cookie/commit/b43b4e9ad25dfc6e035cc50723f39cf3477facae.

Would you be interested in React Native support or do you specifically target just NodeJS? I can provide a PR if such a feature is welcome!

**Comment by pe-johndpope** [comment]
need this.
