### ISSUE TITLE
domainMatch() breaks for URLs with TLD in substring of subdomain

### ISSUE THREAD

**Issue by davidofwatkins** [salesforce/tough-cookie#235]
There's a bug where `domainMatch()` returns `false` unexpectedly when the `domStr` argument (top-level-domain) can be found elsewhere in the domain (`str` argument). For example:

❌  Broken:

```js
require('tough-cookie').domainMatch('computer.com', 'com'); // false - should be true
```

✅  Working:

```js
require('tough-cookie').domainMatch('c0mputer.com', 'com'); // true
```

The issue appears to come from the `indexOf()` check here:

https://github.com/salesforce/tough-cookie/blob/30246e6c039f91ca33fab2046ffdf7a2d3d8c33c/lib/cookie.js#L371

...causing this calculation to fail:

https://github.com/salesforce/tough-cookie/blob/30246e6c039f91ca33fab2046ffdf7a2d3d8c33c/lib/cookie.js#L379-L381

**Comment by colincasey** [comment]
Thanks for the bug report @davidofwatkins.  I'll look into this as soon as possible.  But don't let that deter you from submitting your own PR with a fix if you have one.
