### ISSUE TITLE
expensive blocking PSL lookup

### ISSUE THREAD

**Issue by jjason685** [salesforce/tough-cookie#239]
https://github.com/salesforce/tough-cookie/blob/9b101310dd73f55b71e8120f50b9629e91ee0121/lib/pubsuffix-psl.js#L67

at high throughputs, PSL lookups can be quite intensive. for example, with 1000 calls to psl.get, this can take 400 milliseconds, and completely blocks the event loop. this seems to relatively linearly scale with more calls.

a recommendation is to use a simple Map cache; for example, 

`return psl.get(domain);` 

would be transformed to

```
if (!cache.has(domain)) {
   cache.set(domain, psl.get(domain));
}

return cache.get(domain);
```

(with cache initialized at the top as a new Map).

As the psl.get results are static, this would only benefit the performance, with no drawbacks.

**Comment by colincasey** [comment]
@jjason685 thanks for reporting this.  We'll look into adding a cache around the PSL lookup as you suggested.

**Comment by isaacl** [comment]
See #338 for a more explicit request
