### ISSUE TITLE
Unable to get Cookies

### ISSUE THREAD

**Issue by abhi-car** [salesforce/tough-cookie#244]
Hello Everyone, I have few cookies stored with domain .xxxx.local 

when i did 

 `
const jar = new CookieJar();
    const cookies = jar.getCookiesSync('http://xxxx.local');

    console.log('cookies', cookies);
    const cookies1 = jar.getCookiesSync('http://app.xxxx.local');

    console.log('cookies', cookies1);
    const cookies2 = jar.getCookiesSync('http://app1.xxxx.local');

    console.log('cookies', cookies2);
    const cookies3 = jar.getCookiesSync('.xxxx.local');

    console.log('cookies', cookies3);
`

I got empty arrays. what is the way to get the cookies.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/82850003/183984658-396bc768-7cac-460e-a6f7-aaf7910169a7.png">

_Originally posted by @abhi-car in https://github.com/salesforce/tough-cookie/issues/85#issuecomment-1211071788_

**Comment by colincasey** [comment]
@abhi-car can you include how are you setting the cookie and creating the cookie store?  Without seeing that I have to assume that those cookies are not being set because `.local` is a special-use domain.

See https://github.com/salesforce/tough-cookie#cookiejarstore-options

**Comment by wjhsf** [comment]
Closing because due to lack of response; presumably the usage issue has been resolved.
