### ISSUE TITLE
pubsuffix-psl isn't recognizing localhost correctly

### ISSUE THREAD

**Issue by CSchulz** [salesforce/tough-cookie#248]
I have seen that the implementation of pubsuffix-psl isn't recognizing localhost correctly.

I have checked the complete stacktrace for our local environment using localhost as URL.

```
CookieJar.getCookieStringSync(this.URL, { http: false })
CookieJar.getCookieString(this.URL, { http: false })
CookieJar.getCookies(this.URL, { http: false })
Memstore.findCookies(host = 'localhost', path = '/', allowSpecialUseDomain = true)
permuteDomain(domain = 'localhost', allowSpecialUseDomain = true)
pubsuffix.getPublicSuffix(domain = 'localhost', allowSpecialUseDomain = true)
```

The getPublicSuffix function needs to be called with ignoreError to prevent throwing an error.
In my honest opinion the throw should handle ignoreError and allowSpecialUseDomain cases.

ignoreError: true, allowSpecialUseDomain: false -> no Error
ignoreError: true, allowSpecialUseDomain: true -> no Error
ignoreError: false, allowSpecialUseDomain: false -> throw Error
ignoreError: false, allowSpecialUseDomain: false -> no Error

https://github.com/salesforce/tough-cookie/blob/master/lib/pubsuffix-psl.js#L43-L68

Workaround: use localhost.local for your environment to skip this issue.

**Comment by awaterma** [comment]
We really don't need two issues opened on this in the tracker. :) We are working on a fix and a patch release for tomorrow.

Please continue to reference the issue in #246!
