### ISSUE TITLE
CookieJar not properly setting initial configuration options?

### ISSUE THREAD

**Issue by rommms07** [salesforce/tough-cookie#252]
Good day,

I was trying to setup my own Preact SSR environment (using JSDOM) when I encountered an issue with setting the options of `new CookieJar(..., <options>)` in the JSDOM options and upon running the server, it gives me an error whenever I am trying to access the cookie store (CookieJar) via `document.cookie`, here is the stack trace:

```
/home/rom/Documents/WebFolder/.wip/preact-starter/node_modules/tough-cookie/lib/pubsuffix-psl.js:62
    throw new Error(
          ^

Error: Cookie has domain set to the public suffix "localhost" which is a special use domain. To allow this, configure your CookieJar with {allowSpecialUseDomain:true, rejectPublicSuffixes: false}.
    at Object.getPublicSuffix (/home/blahblah/Documents/WebFolder/.wip/preact-starter/node_modules/tough-cookie/lib/pubsuffix-psl.js:62:11)
    at permuteDomain (/home/blahblah/Documents/WebFolder/.wip/preact-starter/node_modules/tough-cookie/lib/permuteDomain.js:38:28)
    at MemoryCookieStore.findCookies (/home/blahblah/Documents/WebFolder/.wip/preact-starter/node_modules/tough-cookie/lib/memstore.js:99:21)
```

Upon reading the `To allow this, configure your CookieJar...` message I added the mentioned necessary options to the `new Cookie()` and try to re-run the server, but to no luck it still gives me the same error about CookieJar using a special use domain..

I tried console logging the options at `Object.getPublicSuffix` it seems that the options that I've set (those that are mentioned by the error) was now gone! only the `allowSpecialUseDomain` was left. Is this the intention of the author of the function? or is there some underlying part in the `tough-cookie` library that modifies the options that I have passed?

I hope that this post is as clear as a crystal to you, English is not my native language.

**Comment by rommms07** [comment]
Nevermind, I'm gonna close this issue now! I found a work around to this, instead of using a special use domain.. I instead use those that are qualified to the PSL list as my url in the JSDOM options. :P

**Comment by awaterma** [comment]
We've corrected this issue for `localhost` and `invalid` special-case special-use domains in 4.1.2. :)

**Comment by rommms07** [comment]
Thank you for replying to this post, upon reviewing the recent commits I noticed that this issue was already corrected! I guess this is an issue with `jsdom/jsdom` as they are still using `tough-cookie:4.0.0`
