### ISSUE TITLE
url-parse critical security patch

### ISSUE THREAD

**Issue by r4d** [salesforce/tough-cookie#260]
url-parse security advisory update: https://github.com/advisories/GHSA-hgjh-723h-mx2j

Update url-parse > v1.5.8

**Comment by Dremuchev** [comment]
Authorization Bypass Through User-Controlled Key in NPM url-parse prior to 1.5.9.

**Comment by AndyDudleyAdvanced** [comment]
Hi,

Is there any reason why the reference to url-parse hasn't been updated to the patched version? (1.5.9)

**Comment by colincasey** [comment]
@AndyDudleyAdvanced when you `npm install tough-cookie` it should resolve the `url-parse` dependency to version `1.5.10` since the range declared in [package.json](https://github.com/salesforce/tough-cookie/blob/master/package.json#L108) is `^1.5.3`.

**Comment by colincasey** [comment]
Closing this issue since the version of `url-parse` resolved when installing `tough-cookie` is not affected by https://github.com/advisories/GHSA-hgjh-723h-mx2j (see the comment above).
