### ISSUE TITLE
FindCookies function inside memstore.js does not catch the error thrown by permuteDomain function.

### ISSUE THREAD

**Issue by dev-sharma-08** [salesforce/tough-cookie#272]
`permuteDomain` fn calls `getPublicSuffix` fn from `pubsuffix-psl.js` file which throws error upon using `SPECIAL_USE_DOMAINS`.
This error is not handled anywhere which causes unintended crashes.

**Comment by dev-sharma-08** [comment]
Hi @wjhsf, thanks for the quick reply. But even when `allowSpecialDomain` is set as true but the domain part length is less than one, it throws error.

**Comment by wjhsf** [comment]
We've refactored this a bit in v5 and moved from `psl` to `tldts`. If the issue persists in v5, please open a new issue with example code that causes the error to occur.
