### ISSUE TITLE
Can url-parse library be dropped?

### ISSUE THREAD

**Issue by DanEscudero** [salesforce/tough-cookie#278]
Hello!

According to url-parse README file (https://www.npmjs.com/package/url-parse):

> url-parse was created in 2014 when the WHATWG URL API was not available in Node.js and the URL interface was supported only in some browsers. Today this is no longer true. The URL interface is available in all supported Node.js release lines and basically all browsers. Consider using it for better security and accuracy.

I wonder if url-parse is still necessary in this library, or it can be abandoned and URL be used instead. Is there any particular reason not to do this?
If this is ok, I'd be available to submit a Pull Request that does the work

**Comment by awaterma** [comment]
Thank you @DanEscudero for pointing this out. We'd love a pull request if you'd like to submit a fix. We have all been really busy with our day jobs, so it may take a little while to review and merge. But we'd greatly appreciate the help! :)

**Comment by wjhsf** [comment]
I believe that the `url-parse` library was originally added to support React Native, which does not have node's `url` library or a global `URL` object. I don't have any experience with React Native, so perhaps the situation has changed, but I assume that removing `url-parse` would cause things to break. We don't explicitly support React Native, but to avoid any unnecessary negative impacts we'd want to save this for a major release.
