### ISSUE TITLE
`validators.isObject()` uses unreliable `toString` global function

### ISSUE THREAD

**Issue by corvidism** [salesforce/tough-cookie#405]
Hi,

this is bug report is mostly a PSA because you've already fixed it in the current `dev` branch, but maybe I'll save someone some time:

The validation added in `tough-cookie@4.1.0`, specifically the `isObject` function, fails in an environment that overrides the global `toString` method - for example, in a Jest test running in the `jsdom` environment. 

### What happens

Trying to create a new jar with `new CookieJar()` throws error `[object Object]`. 

### Why

When you adapted the validator functions from `check-types`, you didn't bring over [the locally defined `toString` function](https://gitlab.com/philbooth/check-types.js/-/blob/master/src/check-types.js?ref_type=heads#L76). That's fine in theory, the global object has a `toString` method, but it breaks if something redefines it - for example the `jsdom` environment, which replaces the default node global with a mocked `window`, where the `toString` method always returns `undefined`.

### Temporary fix

Before creating the jar, define `window.toString` again:

```js
window.toString = Object.prototype.toString;
```
--- 

The upcoming TS refactor should fix this - the new `objectToString` function uses  [uses `Object.prototype.toString` as expected](https://github.com/salesforce/tough-cookie/blob/master/lib/utils.ts#L16)) - but I'd be happy to submit a pull request. I mean. It's literally one line of code :D.

**Comment by colincasey** [comment]
Thanks for opening this issue and providing a temporary workaround for those who may be affected @corvidism ❤️  

We'd gladly accept a PR fix for this. Most of our maintainer focus has been on preparing for the upcoming TS refactor so fixing this in `4.1.x` is less of a priority at the moment.

**Comment by corvidism** [comment]
Great, I'll do that.

**Comment by wjhsf** [comment]
Fixed in #409.
