### ISSUE TITLE
Methods don't show up

### ISSUE THREAD

**Issue by brunonevesy** [salesforce/tough-cookie#415]
The methods removeCookie never show up, below is the code:

async function Funcao() {
    try {
        
                
        const tough = require('tough-cookie'); // tough-cookie
        const cookieJar = new tough.CookieJar();

        cookieJar.setCookieSync('did=XPTO1; Max-Age=31557600; Path=/; Expires=Sat, 31 May 2025 01:40:02 GMT; HttpOnly; Secure; SameSite=None', 'https://ABC.com');
        cookieJar.setCookieSync('did_compat=XPTO2; Max-Age=31557600; Path=/; Expires=Sat, 31 May 2025 01:40:02 GMT; HttpOnly; Secure', 'https://ABC.com');
        cookieJar.setCookieSync('__cf_bm=XPTO3; path=/; expires=Thu, 30-May-24 20:10:02 GMT; domain=.eu.ABC.com; HttpOnly; Secure; SameSite=None', 'https://ABC.com');

        var cookie = cookieJar.getCookies('https://ABC.com');

        if (cookie) {

            cookieJar.store.removeCookie(cookie.domain, cookie.path, cookie.key, (err) => {
                if (err) {
                    console.error('Erro ao remover cookie:', err);
                    return;
                }
                console.log(`Cookie removido com sucesso`);
            })
            
        }

        console.log("breakpoint");

    } catch (error) {
        console.log(error)
    } finally {

    }
}Funcao()

**Comment by wjhsf** [comment]
The reason you aren't seeing the callback being called is because the following line causes an error to be thrown before `removeCookie` is called.

```js
cookieJar.setCookieSync('__cf_bm=XPTO3; path=/; expires=Thu, 30-May-24 20:10:02 GMT; domain=.eu.ABC.com; HttpOnly; Secure; SameSite=None', 'https://ABC.com');
```

**Comment by colincasey** [comment]
@brunonevesy, For the following code:

```js
var cookie = cookieJar.getCookies('https://ABC.com');
```

Because you aren't providing a callback, the value of `cookie` will be a `Promise<Cookie[]>` ([see docs](https://github.com/salesforce/tough-cookie/blob/master/api/docs/tough-cookie.cookiejar.getcookies_2.md)), not an array of cookies. 

But once you get the array of cookies back, the code you provided below still won't work unless you make significant changes:

```js
// this check is not necessary, the result of successfully retrieving cookies is always Cookie[]
if (cookie) {
  // the cookies are not being iterated over, so `cookie` is currently an array value 
  // which doesn't have properties named `domain` or `path` or `key`
  cookieJar.store.removeCookie(cookie.domain, cookie.path, cookie.key, (err) => {
    if (err) {
      console.error('Erro ao remover cookie:', err);
      return;
    }
    console.log(`Cookie removido com sucesso`);
  })  
}
// the above code is callback-based (async) so if you want this console.log output to show up 
// after all the cookies have been removed that will likely not happen in the order you expect
// unless you add code to wait for all the callbacks to complete
console.log("breakpoint");    
```
