### ISSUE TITLE
Deprecation issue with the 'punycode' module

### ISSUE THREAD

**Issue by valorisa** [salesforce/tough-cookie#456]
Hello,

I am encountering a deprecation issue with the punycode module in your project. The warning message is as follows:

(node:19880) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.

Could you consider updating your project to use a more recent version of punycode (e.g., punycode@2.3.1)?

Thank you in advance for your help.

Best regards,
valorisa

**Comment by wjhsf** [comment]
Duplicate of #315, #324, #338, #348. Fixed by #346. The fix is available in our latest releast, [v5.0.0](https://github.com/salesforce/tough-cookie/releases/v5.0.0).

**Comment by valorisa** [comment]
Thanks
