### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by mike-aungsan** [salesforce/tough-cookie#47]
I cannot use any of these functions.

var t = require('tough-cookie')

var tcj = t.CookieJar()
tcj.fromJSON(JSON)

var tcfj = t.CookieJar.fromJSON(JSON)

The same goes to this function. 

CookieJar.deserialize(serialized, [store], cb(err,object))

A new Jar is created and the serialized Cookies are added to the underlying store. Each Cookie is added via store.putCookie in the order in which they appear in the serialization.

The store argument is optional, but should be an instance of Store. By default, a new instance of MemoryCookieStore is created.

As a convenience, if serialized is a string, it is passed through JSON.parse first. If that throws an error, this is passed to the callback.

Any example or help? 

Many Thanks

**Comment by stash-sfdc** [comment]
What is the format of the JSON you're feeding in? Did it come from a `.toJSON` or `.serialize` call? Maybe you can paste us an example.

Do you get any exceptions, stack-traces, or error messages?
