### ISSUE TITLE
tough.CookieJar.deserialize removes the cookies from the input object

### ISSUE THREAD

**Issue by dotchev** [salesforce/tough-cookie#59]
It seems `tough.CookieJar.deserialize` removes the cookies from the input object.

For example this code
```js
  console.log('*** before deserialize', serializedJar);
  tough.CookieJar.deserialize(serializedJar, function (err, cookieJar) {
    console.log('*** after deserialize', serializedJar);
    ...
  });
```
produces this result
```
*** before deserialize { version: 'tough-cookie@2.2.0',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies:
   [ { key: 'JSESSIONID2',
       value: 's%3ABIIawEU9ZRUERfwgjmOxhCgRMneLeE-i.xbzgSn4JqDU2RMRaX5URdEED8szBEuOHIti0XYV%2Beh0',
       domain: 'localhost',
       path: '/',
       httpOnly: true,
       hostOnly: true,
       creation: '2016-01-20T13:08:36.448Z',
       lastAccessed: '2016-01-20T13:08:36.448Z' } ] }
*** after deserialize { version: 'tough-cookie@2.2.0',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies: [] }
```
As you can see `serializedJar` argument is modified after the call to `deserialize`.

The reason seems to be this code `cookies.shift()`
https://github.com/SalesforceEng/tough-cookie/blob/master/lib/cookie.js#L1227

I find this side effect rather surprising.
For example if you deserialize twice the same object, you will get different results.

**Comment by inikulin** [comment]
Calling `cookies = cookies.slice()` [here](https://github.com/SalesforceEng/tough-cookie/blob/master/lib/cookie.js#L1215) should solve the problem. Would you like to contribute your first shiny PR to the tough-cookie :wink: ?
