### ISSUE TITLE
Regular expressions for (LOOSE_)COOKIE_PAIR are incorrect

### ISSUE THREAD

**Issue by iamstolis** [salesforce/tough-cookie#63]
The regular expression for COOKIE_PAIR is /^(([^=;]+))\s_=\s_(("?)[^\n\r\0]*\3)/ see https://github.com/SalesforceEng/tough-cookie/blob/master/lib/cookie.js#L61

The intention of the back-reference \3 is to match the group ("?), i.e., the value may or may not be enclosed in quotes. Unfortunately, this is not the 3rd but 4th group. The groups are numbered according to their left parenthesis. So:
\1 is (([^=;]+))
\2 is ([^=;]+)
\3 is (("?)[^\n\r\0]*\3)
\4 is ("?)
The current regular expression matches the cookies only because JavaScript engines ignore nested (note that \3 is in the group it refers to) back-references (i.e. they match them to an empty string).

There is the same problem with LOOSE_COOKIE_PAIR at https://github.com/SalesforceEng/tough-cookie/blob/master/lib/cookie.js#L65

I am leaving aside whether the rest of the regular expression is correct but at minimum the \3 back-reference should be changed to \4 to follow its intention.

**Comment by inikulin** [comment]
Nice catch. Can you issue a PR with regression test and fix, please?

**Comment by iamstolis** [comment]
OK, I will do it in few days.

**Comment by iamstolis** [comment]
PR #64

**Comment by stash-sfdc** [comment]
LGTM. @iamstolis could you please contact me at jstashewsky@salesforce.com and I can get you the CLA.

**Comment by stash** [comment]
tough-cookie no longer uses regexp for parsing, so probably this is now irrelevant.
