### ISSUE TITLE
Idea: promises

### ISSUE THREAD

**Issue by jimmywarting** [salesforce/tough-cookie#66]
would like promises (async/await) instead of callbacks...
We could have both...

**Comment by inikulin** [comment]
Great idea! PR is welcome

**Comment by szmarczak** [comment]
@stash Any updates?

**Comment by mbrucher** [comment]
Would be great to use this, as I'm currently deep inside trying to use tough cookie getCookies inside a stream of promises, and only tough cookie break my code with no clear way of sorting this out :/

**Comment by PixnBits** [comment]
Looks like this is coming in [4.x](https://github.com/salesforce/tough-cookie/milestone/4?closed=1) via #157 👍

**Comment by awaterma** [comment]
We have both now. Closing.
