### ISSUE TITLE
package.json is required thus packed by browserify

### ISSUE THREAD

**Issue by fundkis** [salesforce/tough-cookie#72]
Hi,
we indirectly use your library on browser side thanks to browserify and I realized that the generated code contains your package.json (after some npm transformation).
this is due to the instruction `require('../package.json').version` in `./lib/cookie.js`
I don't see any good solution to keep the version in one place and avoiding to require the package.json unless you add some preprocessing to update package.json....

**Comment by stash** [comment]
Intend to fix this with `genversion`
