### ISSUE TITLE
Punycode AMD error with RequireJS

### ISSUE THREAD

**Issue by paul321** [salesforce/tough-cookie#82]
We get the following error TypeError: punycode.toASCII is not a function when using node request that uses this library, the problem is with punycode 1.4.1 which doesn't work with AMD. Please update dependencies to 2.0.1

Thank you

**Comment by stash** [comment]
Triage: Will consider the upgrade still, but tough-cookie needs to be pretty backwards compatible due to lots of packages depending on us. Currently, `punycode` depends on `node >= 6` and `tough-cookie` supports `node >= 0.8` (but technically we only test 0.10+)
