### ISSUE TITLE
How to get a value of a cookie provided a cookie jar?

### ISSUE THREAD

**Issue by gajus** [salesforce/tough-cookie#85]
It is not entirely clear from the documentation how to get a value of a specific cookie provided an instance of a `CookieJar`.

```js
// This always gives me a single item array.
// It is not clear from the documentation when the result would contain more than entry.
const cookies = jar.getCookiesSync(guide.result.url);

> [ Cookie="ASP.NET_SessionId=gqwdcucn4iqdztwcvqr3xmpy; Expires=Wed, 17 Mar 2027 16:00:50 GMT; Domain=foo.com; Path=/; HttpOnly; HttpOnly,SC_ANALYTICS_GLOBAL_COOKIE=4e3659e87284422c8dd691f35b1a622e|False; HttpOnly,UserSessionId=af5abf42-e3c9-4478-a1c7-61300614dc8c|10002|181845|161471|2017-03-17; hostOnly=false; aAge=0ms; cAge=2ms" ]

// This is supposed to parse the cookie-string into a `Cookie` object.
Cookie.parse(cookies[0]);

```

Using `Cookie.parse` in the above example I am getting an error:

> TypeError: str.trim is not a function
>    at Function.parse (/Users/gajus/Documents/dev/foo/node_modules/tough-cookie/lib/cookie.js:325:13)
>    at exports.scrapeTickets (/Users/gajus/Documents/dev/applaudience/foo/src/countries/foo.js:122:23)
>    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by inikulin** [comment]
> // This is supposed to parse the cookie-string into a `Cookie` object.
Cookie.parse(cookies[0]);

`Cookie.parse` parses cookie string like the one you set in browser for `document.cookie`. `jar.getCookiesSync` returns array of data structures that represent **already parsed** cookie. Thus, to access `value` of the particular cookie you need to scan returned array for required `key` and use it's `value` property. If you need to get string representation of the current cookie jar like the one that returned by browser in `Cookies` header, then you can use `jar.getCookieString` method. This interactive example shows both approaches: https://runkit.com/580f9ad527cf550013c20537/58cc1078e26e580014605e9e

**Comment by gajus** [comment]
Oh I see. What confused me is that `Cookie` implements (I am guessing) a `toString` method, which makes it look like the result of the `getCookieSync` is an array of strings.

```
[ Cookie="ASP.NET_SessionId=gqwdcucn4iqdztwcvqr3xmpy; Expires=Wed, 17 Mar 2027 16:00:50 GMT; Domain=foo.com; Path=/; HttpOnly; HttpOnly,SC_ANALYTICS_GLOBAL_COOKIE=4e3659e87284422c8dd691f35b1a622e|False; HttpOnly,UserSessionId=af5abf42-e3c9-4478-a1c7-61300614dc8c|10002|181845|161471|2017-03-17; hostOnly=false; aAge=0ms; cAge=2ms" ]

```

**Comment by gajus** [comment]
This is starting to look like a bug, or I am completely misunderstanding something.

The server responds with:

```
Set-Cookie:              ASP.NET_SessionId=4pxd5fecgvg2vaq1nyetxk5z; domain=foo.com; path=/; HttpOnly
Set-Cookie:              SC_ANALYTICS_GLOBAL_COOKIE=a17765ea49144afdb045dac1294323ca|False; domain=foo.com; expires=Wed, 17 Mar
                         2027 17:12:37 -0000; path=/; HttpOnly
Set-Cookie:              UserSessionId=7c47a144-6a12-4ffc-907a-db8a281cca6a|10002|181845|161471|2017-03-17; domain=foo.com; path=/;
                         HttpOnly
```

I do:

```js
const cookies = jar.getCookiesSync(guide.result.url);

console.log('cookies', cookies);

const userSessionId = _.find(cookies, (cookie) => {
  console.log('>>>', cookie.key);

  return false;
});

```

which gives:

```
cookies [ Cookie="ASP.NET_SessionId=gqwdcucn4iqdztwcvqr3xmpy; Expires=Wed, 17 Mar 2027 17:20:32 GMT; Domain=myvue.com; Path=/; HttpOnly; HttpOnly,SC_ANALYTICS_GLOBAL_COOKIE=4e3659e87284422c8dd691f35b1a622e|False; HttpOnly,UserSessionId=af5abf42-e3c9-4478-a1c7-61300614dc8c|10002|181845|161471|2017-03-17; hostOnly=false; aAge=0ms; cAge=1ms" ]
>>> ASP.NET_SessionId

```

It looks like it only picked up only the first `set-cookie`.

**Comment by gajus** [comment]
Just to make it clearer whats the contents of the `cookies`.

```js
const cookies = jar.getCookiesSync('http://foo.com');

console.log('cookies', cookies);

const userSessionId = _.find(cookies[0], (cookie) => {
  console.log('>>>', cookie);

  return false;
});
```

```
cookies [ Cookie="ASP.NET_SessionId=4pxd5fecgvg2vaq1nyetxk5z; Expires=Wed, 17 Mar 2027 18:19:00 GMT; Domain=foo.com; Path=/; HttpOnly; HttpOnly,SC_ANALYTICS_GLOBAL_COOKIE=a17765ea49144afdb045dac1294323ca|False; HttpOnly,UserSessionId=7c47a144-6a12-4ffc-907a-db8a281cca6a|10002|181845|161471|2017-03-17; hostOnly=false; aAge=0ms; cAge=2ms" ]
>>> 2017-03-17T17:16:32.481Z
>>> ASP.NET_SessionId
>>> 4pxd5fecgvg2vaq1nyetxk5z
>>> myvue.com
>>> /
>>> [ 'HttpOnly,SC_ANALYTICS_GLOBAL_COOKIE=a17765ea49144afdb045dac1294323ca|False',
  'HttpOnly,UserSessionId=7c47a144-6a12-4ffc-907a-db8a281cca6a|10002|181845|161471|2017-03-17' ]
>>> 2027-03-17T18:19:00.000Z
>>> true
>>> false
>>> 2017-03-17T17:16:32.483Z

```

**Comment by gajus** [comment]
Turns out a bug in the HTTP client, https://github.com/gajus/xfetch/commit/71449accb4fd220b199b5f07e7107b5c5abbd76a.

**Comment by abhi-car** [comment]
Hello Everyone, I have few cookies stored with domain .xxxx.local. when i did 
`const jar = new CookieJar();
    const cookies = jar.getCookiesSync('http://xxxx.local');

    console.log('cookies', cookies);
    const cookies1 = jar.getCookiesSync('http://app.xxxx.local');

    console.log('cookies', cookies1);
    const cookies2 = jar.getCookiesSync('http://app1.xxxx.local');

    console.log('cookies', cookies2);
    const cookies3 = jar.getCookiesSync('.xxxx.local');

    console.log('cookies', cookies3);`

I got empty arrays. what is the way to get the cookies.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/82850003/183984658-396bc768-7cac-460e-a6f7-aaf7910169a7.png">
