### ISSUE TITLE
Feature request: remove all cookies from cookie jar at once

### ISSUE THREAD

**Issue by olalonde** [salesforce/tough-cookie#93]
It would be helpful to have a method to completely clear the cookie jar.

**Comment by tizmagik** [comment]
May I suggest:

```js
var tough = require('tough-cookie');
var cookiejar = new tough.CookieJar();
cookiejar.cookieMonsterNomNom();
```

**Comment by ichernev** [comment]
+1

As a workaround you can switch the current jar with a brand new one, but removing all cookies is a very meaningful addition.

**Comment by stash-sfdc** [comment]
This probably means adding `Store#removeAllCookies` (to pair with the existing `#removeCookies`) and then having `CookieJar#removeAllCookies`.

**Comment by lewebsimple** [comment]
Can't we just delete the jar and create a new instance ?

**Comment by jamiehaywood** [comment]
any movement on this FeatureRequest?

**Comment by jamiehaywood** [comment]
@awaterma has this been removed from the backlog?

**Comment by ShivanKaul** [comment]
@jamiehaywood  this was done in #115, going to close this issue.
